# Generated by Django 4.1.7 on 2023-02-16 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uspcldh', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlashNew',
            new_name='FlashNews',
        ),
    ]
