# Generated by Django 4.1.7 on 2023-02-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uspcldh', '0003_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
